import type { Article } from "./schema";

const today = new Date().toISOString().split("T")[0];

export const mockArticles: Article[] = [
  {
    id: 1,
    title: "DeepSeek V4 Flash Redefines Cost-Performance Tradeoff for Agentic AI",
    summary:
      "DeepSeek's latest release achieves near-GPT-4 performance at a fraction of the cost, making autonomous agent pipelines economically viable for indie developers and small teams for the first time. Benchmarks show particular strength in multi-step reasoning and tool use — the two capabilities most critical for production workflows.",
    source: "The Verge",
    sourceUrl: "https://theverge.com",
    category: "tech",
    subcategory: "AI",
    bias: null,
    publishedAt: today,
    readingTimeMinutes: 4,
    importanceScore: 0.95,
    imageUrl: "https://picsum.photos/seed/ai-flash/1200/675",
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Sequoia Leads $120M Series B Into AI Infrastructure Play Foundry",
    summary:
      "Foundry, a two-year-old startup building GPU orchestration middleware, closes its Series B as compute demand shows no signs of slowing. The round values the company at $800M and will fund expansion into European data centers.",
    source: "TechCrunch",
    sourceUrl: "https://techcrunch.com",
    category: "tech",
    subcategory: "VC",
    bias: null,
    publishedAt: today,
    readingTimeMinutes: 3,
    importanceScore: 0.78,
    imageUrl: "https://picsum.photos/seed/vc-round/1200/675",
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: "MIT Study Links Transformer Attention Heads to Human Working Memory",
    summary:
      "Neuroscientists and ML researchers at MIT publish findings suggesting that multi-head attention in large language models mirrors the capacity limits and interference patterns seen in human working memory. The result has implications for both AI alignment and cognitive science.",
    source: "Nature",
    sourceUrl: "https://nature.com",
    category: "tech",
    subcategory: "Research",
    bias: null,
    publishedAt: today,
    readingTimeMinutes: 6,
    importanceScore: 0.88,
    imageUrl: null,
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: "Linear Launches AI-Native Project Management With Context-Aware Triage",
    summary:
      "Linear's new AI layer automatically routes, prioritizes, and drafts responses to incoming issues by learning from team history. Early access customers report a 40% reduction in triage time in the first week of use.",
    source: "Product Hunt",
    sourceUrl: "https://producthunt.com",
    category: "tech",
    subcategory: "Product",
    bias: null,
    publishedAt: today,
    readingTimeMinutes: 2,
    importanceScore: 0.71,
    imageUrl: null,
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: "Critical Zero-Day in Widely-Used npm Package Exposes 2M Projects",
    summary:
      "Security researchers disclose a remote code execution vulnerability in a popular build-time dependency with over 2 million weekly downloads. A patch is available; project maintainers are urged to update immediately.",
    source: "Wired",
    sourceUrl: "https://wired.com",
    category: "tech",
    subcategory: "Security",
    bias: null,
    publishedAt: today,
    readingTimeMinutes: 3,
    importanceScore: 0.92,
    imageUrl: null,
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    title: "Senate Passes Sweeping AI Liability Bill in 67-31 Bipartisan Vote",
    summary:
      "The Algorithmic Accountability Act clears the Senate with unexpected Republican support after months of heated debate. The bill holds developers financially liable for harms caused by AI systems above a defined capability threshold and mandates third-party audits for high-risk deployments.",
    source: "Reuters",
    sourceUrl: "https://reuters.com",
    category: "politics",
    subcategory: null,
    bias: "center",
    publishedAt: today,
    readingTimeMinutes: 5,
    importanceScore: 0.97,
    imageUrl: "https://picsum.photos/seed/senate-vote/1200/675",
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    title: "White House Executive Order on AI Draws Fire From Both Parties",
    summary:
      "The administration's latest executive order on AI development has united progressive and libertarian critics for opposite reasons — the left argues it doesn't go far enough on safety, while industry-aligned Republicans call it regulatory overreach that will stifle innovation.",
    source: "Fox News",
    sourceUrl: "https://foxnews.com",
    category: "politics",
    subcategory: null,
    bias: "right",
    publishedAt: today,
    readingTimeMinutes: 4,
    importanceScore: 0.83,
    imageUrl: "https://picsum.photos/seed/white-house/1200/675",
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    title: "Tech Workers Stage Walkout Over Defense Contracts, Citing Moral Injury",
    summary:
      "Hundreds of engineers at three major tech firms staged coordinated walkouts citing concerns over AI contracts with the Defense Department. Organizers say more actions are planned until companies publish binding ethical use policies for government work.",
    source: "The Guardian",
    sourceUrl: "https://theguardian.com",
    category: "politics",
    subcategory: null,
    bias: "left",
    publishedAt: today,
    readingTimeMinutes: 4,
    importanceScore: 0.76,
    imageUrl: null,
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    title: "EU Digital Markets Act Enforcement Arm Targets Apple, Meta in Dual Probe",
    summary:
      "European regulators open simultaneous investigations into Apple's App Store fee structure and Meta's data portability compliance, marking the most aggressive use of DMA enforcement powers since the act took effect. Potential fines could reach 10% of global annual turnover.",
    source: "Financial Times",
    sourceUrl: "https://ft.com",
    category: "politics",
    subcategory: null,
    bias: "center",
    publishedAt: today,
    readingTimeMinutes: 5,
    importanceScore: 0.85,
    imageUrl: null,
    digestDate: today,
    createdAt: new Date().toISOString(),
  },
];
